server:
  port: 8095
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:1001
  application:
    name: gulimall-auth-server
  redis:
    host: localhost
    port: 6379
    password: 123456
  session:
    store-type: redis
    timeout: 30m
