spring:
  application:
    name: gulimall-seckill
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:1001
  redis:
    host: localhost
    port: 6379
    password: 123456
  session:
    store-type: redis
  rabbitmq:
    virtual-host: /
server:
  port: 8092
