spring:
  cloud:
    alicloud:
      access-key: LTAI5tL2Q2HXegQwf9qr4L3S
      secret-key: W8xfUZLTvAtanXBDyITqH2H9dFMgzP
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: yuan-1006969989
  application:
    name: gulimall-third-party
server:
  port: 8099
