spring:
  cloud:
    alicloud:
      access-key:
      secret-key:
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: yuan-1006969989
  application:
    name: gulimall-third-party
server:
  port: 8099
