server:
  port: 8098
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:1001
  application:
    name: gulimall-cart
  redis:
    host: localhost
    port: 6379
    password: 123456
  session:
    store-type: redis
